### PR TITLE
Update/add (fav)icons

### PR DESCRIPTION
**Pull request by xf-**
Can be tested and created with http://realfavicongenerator.net/

### CODE REVIEW

**Comment by jplitza** [comment]
Wow, I really hate those browser developers each doing their own thing instead of agreeing on a standard. Thanks for putting this up!

Some thoughts on this:
* Can we put some of these images into subdirectories, ideally in the images/logo subrepository?
* Why is there so much space around the mstile?
* Why did you remove the transparency of the apple-touch-icon?
* Can't the safari-pinned-tab.svg simply be the original SVG? (Yes, I have FreifunkBremen/logo#2 in mind. I'm especially wondering whether the SVG has to have any special format, because yours differs very much from the original w.r.t. the source code)

**Comment by xf-** [comment]
Most stuff is from Mobile devices:

 Can we put some of these images into subdirectories, ideally in the images/logo subrepository?
Yes, regenerate the stuff and add the stuff. It will add 2 new meta tags and adopt paths in xml and json

Why is there so much space around the mstile?
Good Question, is normal default style, Windows is strange. I used the generator. Windows has x Tiles and i don't with in Windows 10 are widely used. Nice gimmick for launcher.

Why did you remove the transparency of the apple-touch-icon?
Generator again. I think most mobile devices use some sort of tiles/background color and to ensure contrast it was white. Also without alpha it is smaller.

Can't the safari-pinned-tab.svg simply be the original SVG? (Yes, I have FreifunkBremen/logo#2 in mind. I'm especially wondering whether the SVG has to have any special format, because yours differs very much from the original w.r.t. the source code)
Never tested it, but i think only monochrome with a color information is supported. https://github.com/FreifunkBremen/bremen.freifunk.net/pull/25/files#diff-2c19d9859b055d0302043d0fa2833e3fR15

**Comment by Timi7007** [comment]
As requested on IRC I tested the functionality on some real devices.

ffhb.de-pinned-to-start-edge
This is the icon pinned to the start menu of Windows 10 using Egde in middle and small. No other size available. I don't really like the background color. The gray thing is the hover. Also tried Windows 8. More or less the same thing.

ffhb.de-pinned-to-home-iPad
This is from an iPad. Pinned with Safari. If it would not work, it would simply show a screenshot of the site as the icon.

[Pinning to start on Android using Chrome also works. It creates a nameable link and acts like an app. I like the way it looks (in Chrome and as "app").](https://youtu.be/WPfx0ak-Uwo)

Didn't test MacOS yet.

**Comment by SimJoSt** [comment]
Works for me on Android too.

**Comment by SimJoSt** [comment]
@Timi7007 Do you have any suggestions on how and to what to change the Windows icon?
The logo seems kind of small on that tile. Maybe it could be bigger.

**Pull request merged**
